### ISSUE TITLE
Sempre tenho que conceder acesso a minha aplicação?

### ISSUE THREAD

**Issue by josemarcam** [ContaAzul/api-examples#17]
Bom, eu estou com esse problema, mas acho que pode ser um erro de interpretação de texto meu.

Na documentação, diz o seguinte:

![Captura de Tela 2020-07-16 às 12 15 16](https://user-images.githubusercontent.com/35896719/87688999-11efc180-c75e-11ea-91c9-a2dff6e90d9d.png)
(Esta parte encontra-se na sessão **Authentication**, no tópico **Application is approved**)

Então isso quer dizer que o usuario da minha aplicação terá que dar mais uma vez a permissão para a minha aplicação? Pois se o usuario sair e voltar um tempo depois, o refresh_token não vai adiantar para a aplicação solicitar um token novo, então o usuario tera mais uma vez que conceder acesso para a minha aplicação?

**Comment by ajunior** [comment]
@josemarcam o refresh token tem validade de 14 dias, então só será necessário repetir o processo de autorização se o refresh token expirar, porque isso impedirá a renovação do access token.
